name: Build and Deploy Nextcloud

on:
  push:
    branches:
      - feature/nextcloud-binay-new

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_BINAY }}
          password: ${{ secrets.DOCKERHUB_TOKEN_BINAY }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME_BINAY }}/nextcloud-apache:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME_BINAY }}/nextcloud-apache:latest
 ##...