name: Build and Deploy Nextcloud

on:
  push:
    branches:
      - develop
      - staging
      - feature/nextcloud-sijan

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Extract short commit hash
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_SIJANDEV }}
          password: ${{ secrets.DOKERHUB_TOKEN_SIJANDEV}}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME_SIJANDEV }}/nextcloud-apache:${{ steps.vars.outputs.IMAGE_TAG }} \
            .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME_SIJANDEV}}/nextcloud-apache:${{ steps.vars.outputs.IMAGE_TAG }}
          