name: Build and Deploy Nextcloud

on:
  push:
    branches:
      - develop
      - staging
      - feature/nextcloud-nilam

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Extract short commit hash
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_NILAM }}
          password: ${{ secrets.DOKERHUB_TOKEN_NILAM}}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME_NILAM }}/nextcloud-apache:${{ steps.vars.outputs.IMAGE_TAG }} \
            .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME_NILAM}}/nextcloud-apache:${{ steps.vars.outputs.IMAGE_TAG }}
          
- name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 54.204.180.99
          username: nilam
          key: ${{ secrets.SERVER_SSH_KEY_NILAM }}
          script: |
            cd ${{ secrets./home/nilam/nextcloud-dev }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME_NILAM }}/nextcloud-apache:${{ steps.vars.outputs.TAG }}
            echo "Deploying.."
            sleep 5
            echo done
