name: Build and Deploy Nextcloud

on:
  push:
    branches:
      - feature/nextcloud-dhurba

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_DHURBA }}
          password: ${{ secrets.DOCKERHUB_TOKEN_DHURBA }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME_DHURBA }}/nextcloud-apache:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME_DHURBA }}/nextcloud-apache:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 54.204.180.99
          username: dhurba
          key: ${{ secrets.SERVER_SSH_KEY_DHURBA }}
          script: |
            cd /home/ubuntu/nextcloud-dev1
            docker pull ${{ secrets.DOCKERHUB_USERNAME_DHURBA }}/nextcloud-apache:${{ steps.vars.outputs.TAG }}
            echo "Deploying.."
            sleep 5
            echo done
