name: Build and Deploy Nextcloud

on:
  push:
    branches:
      - feature/nextcloud-deepak-dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_DEEPAK }}
          password: ${{ secrets.DOCKERHUB_TOKEN_DEEPAK }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME_DEEPAK }}/nextcloud-apache:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME_DEEPAK }}/nextcloud-apache:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.218.39.198
          username: deepak
          key: ${{ secrets.SERVER_SSH_KEY_DEEPAK }}
          script: |
            cd /home/deepak/nextcloud-dev
            docker pull ${{ secrets.DOCKERHUB_USERNAME_DEEPAK }}/nextcloud-apache:${{ steps.vars.outputs.TAG }}
            echo "Deploying.."
            sleep 5
            echo done