name: Build and Deploy Nextcloud

on:
  push:
    branches:
      - nextcloud-pokhara/milanad

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Extract short commit hash
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ DOCKERHUB_USERNAME_MILANAD }}
          password: ${{ DOCKERHUB_TOKEN_MILANAD }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ DOCKERHUB_USERNAME_MILANAD }}/nextcloud-apache:${{ steps.vars.outputs.IMAGE_TAG }} \
            .

      - name: Push Docker image
        run: |
          docker push ${{ DOCKERHUB_USERNAME_MILANAD }}/nextcloud-apache:${{ steps.vars.outputs.IMAGE_TAG }}


